import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import CompaniesList from "../components/CompaniesList";
// import { getCompanies } from "./apiRequests";
import axios from "axios";

axios.defaults.baseURL = "https://app.informer.md/api/public";

export default function Home({ companies }) {
  const [name, setName] = useState("");

  const handleChange = (e) => {
    e.preventDefault();
    // console.log(name);
    setName(e.target.value);
  };
  const handleSubmit = () => {
    // getCompanies(name).then((res) => console.log(res));
  };
  // console.log(companies);

  return (
    <div className={styles.container}>
      <h1>
        We help Republic of Moldova&#39;s companies upscale their business and
        minimize potential risks.
      </h1>
      <form>
        <input type="text" onChange={handleChange} value={name} />
        &nbsp;
        <button onClick={handleSubmit}>Search</button>
      </form>
      {/* {companies.data.map((item) => (
        <div key={item.id}>
          <p>{item.id}</p>
          <p>{item.name}</p>
          <p>{item.idno}</p>
          <p>{item.website}</p>
          <p>{item.creation_date}</p>
        </div>
      ))} */}
      <CompaniesList companies={companies.data}></CompaniesList>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}

///////////////////    HOW GET name FROM name state???     ////////////////////

export const getStaticProps = async () => {
  const data = await axios.get(`/search?page=6&per_page=5&company_name=trans`);
  // console.log(data);
  return {
    props: {
      companies: data.data,
    },
  };
};
